### ISSUE TITLE
マイスケジュールで「全てのセッションを見る」を連打すると落ちる

### ISSUE THREAD

**Issue by heki1224** [konifar/droidkaigi2016#119]
#### 現象
- マイスケジュールにセッションが1つも登録されていない状態で「全てのセッションを見る」ボタンを2回連打して押すと、アプリがクラッシュする

**Comment by konifar** [comment]
:eyes: 報告ありがとうございます :+1: 
たしかに起こりそうですね…

これかもです。

```java
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
       at io.github.droidkaigi.confsched.activity.MainActivity.replaceFragment(MainActivity.java:89)
       at io.github.droidkaigi.confsched.activity.MainActivity.lambda$changePage$24(MainActivity.java:142)
       at io.github.droidkaigi.confsched.activity.MainActivity.access$lambda$3(MainActivity.java)
       at io.github.droidkaigi.confsched.activity.MainActivity$$Lambda$4.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
