### ISSUE TITLE
Crash occurred when launching with no internet connection

### ISSUE THREAD

**Issue by yuyakaido** [konifar/droidkaigi2016#133]
### Steps to Reproduce
- Put device into Airplane mode
- Install app and launch

### Stack trace
```
02-11 16:39:25.206 17481-17481/? E/SessionsFragment: Load failed
                                                     retrofit2.HttpException: HTTP 504 Unsatisfiable Request (only-if-cached)
                                                         at retrofit2.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:159)
                                                         at retrofit2.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:154)
                                                         at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                         at retrofit2.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:109)
                                                         at retrofit2.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:88)
                                                         at rx.Observable$2.call(Observable.java:162)
                                                         at rx.Observable$2.call(Observable.java:154)
                                                         at rx.Observable$2.call(Observable.java:162)
                                                         at rx.Observable$2.call(Observable.java:154)
                                                         at rx.Observable$2.call(Observable.java:162)
                                                         at rx.Observable$2.call(Observable.java:154)
                                                         at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:232)
                                                         at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:142)
                                                         at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                         at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                                                         at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                                                         at rx.internal.operators.OperatorToObservableList$1.onCompleted(OperatorToObservableList.java:93)
                                                         at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
                                                         at com.github.gfx.android.orma.Selector$3.call(Selector.java:257)
                                                         at com.github.gfx.android.orma.Selector$3.call(Selector.java:248)
                                                         at rx.Observable$2.call(Observable.java:162)
                                                         at rx.Observable$2.call(Observable.java:154)
                                                         at rx.Observable$2.call(Observable.java:162)
                                                         at rx.Observable$2.call(Observable.java:154)
                                                         at rx.Observable$2.call(Observable.java:162)
                                                         at rx.Observable$2.call(Observable.java:154)
                                                         at rx.Observable$2.call(Observable.java:162)
                                                         at rx.Observable$2.call(Observable.java:154)
                                                         at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                         at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                         at java.lang.Thread.run(Thread.java:841)
02-11 16:39:33.214 17481-17481/io.github.droidkaigi.confsched.develop.debug E/CrashlyticsCore: Failed to execute task.
                                                                                               java.util.concurrent.TimeoutException
                                                                                                   at java.util.concurrent.FutureTask.get(FutureTask.java:173)
                                                                                                   at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
                                                                                                   at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
                                                                                                   at com.google.android.gms.analytics.ExceptionReporter.uncaughtException(Unknown Source)
                                                                                                   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                                   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
                                                                                                   at android.os.Handler.handleCallback(Handler.java:730)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                                   at dalvik.system.NativeStart.main(Native Method)
02-11 16:39:33.214 17481-17481/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                              java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                                                                  at android.os.Handler.handleCallback(Handler.java:730)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                  at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                                                               Caused by: rx.exceptions.OnErrorNotImplementedException: HTTP 504 Unsatisfiable Request (only-if-cached)
                                                                                                  at rx.Observable$26.onError(Observable.java:7881)
                                                                                                  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
                                                                                                  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
                                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                                  at android.os.Handler.handleCallback(Handler.java:730) 
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                                                  at android.os.Looper.loop(Looper.java:137) 
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                  at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                                               Caused by: retrofit2.HttpException: HTTP 504 Unsatisfiable Request (only-if-cached)
                                                                                                  at retrofit2.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:159)
                                                                                                  at retrofit2.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:154)
                                                                                                  at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                                                                  at retrofit2.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:109)
                                                                                                  at retrofit2.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:88)
                                                                                                  at rx.Observable$2.call(Observable.java:162)
                                                                                                  at rx.Observable$2.call(Observable.java:154)
                                                                                                  at rx.Observable$2.call(Observable.java:162)
                                                                                                  at rx.Observable$2.call(Observable.java:154)
                                                                                                  at rx.Observable$2.call(Observable.java:162)
                                                                                                  at rx.Observable$2.call(Observable.java:154)
                                                                                                  at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                                                  at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
                                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                                  at java.lang.Thread.run(Thread.java:841)
```

**Comment by konifar** [comment]
:eyes: 
Oh...Sorry! Thanks for reporting :bow:

**Comment by hotchemi** [comment]
@yuyakaido Thx for your report!

**Comment by hkurokawa** [comment]
Closing the issue as the fix is merged.
