### ISSUE TITLE
App crashes just after launch if upgraded from  PlayStore 1.0.1 to DeployGate 13

### ISSUE THREAD

**Issue by hkurokawa** [konifar/droidkaigi2016#179]
## Description
The app crashed with the below SQL error after upgrading from the current version on Google Play (1.0.1) to the build 13 on DeployGate.

```java
       SessionsFragment  I  Sessions Load succeeded.
              SQLiteLog  E  (1) no such column: share_url
               Settings  W  Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
         AndroidRuntime  E  FATAL EXCEPTION: AsyncTask #1
                         E  Process: io.github.droidkaigi.confsched, PID: 24146
                         E  com.github.gfx.android.orma.exception.TransactionAbortException: android.database.sqlite.SQLiteException: no such column: share_url (code 1): , while compiling: UPDATE "Session"                             SET "share_url"=?,"placeId"=?,"stime"=?,"description"=?,"etime"=?,"speakerId"=?,"slide_url"=?,"title"=?,"categoryId"=?,"movie_url"=?,"language_id"=? WHERE ("id" = ?)
                         E      at com.github.gfx.android.orma.TransactionTask.onError(SourceFile:27)
                         E      at com.github.gfx.android.orma.OrmaConnection.transactionSync(SourceFile:263)
                         E      at com.github.gfx.android.orma.OrmaConnection$2.run(SourceFile:274)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         E      at java.lang.Thread.run(Thread.java:818)
                         E  Caused by: android.database.sqlite.SQLiteException: no such column: share_url (code 1): , while compiling: UPDATE "Session" SET "share_url"=?,"placeId"=?,"stime"=?,"description"                            =?,"etime"=?,"speakerId"=?,"slide_url"=?,"title"=?,"categoryId"=?,"movie_url"=?,"language_id"=? WHERE ("id" = ?)
                         E      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                         E      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                         E      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                         E      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                         E      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                         E      at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                         E      at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1574)
                         E      at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
                         E      at com.github.gfx.android.orma.OrmaConnection.update(SourceFile:168)
                         E      at com.github.gfx.android.orma.Updater.execute(SourceFile:47)
                         E      at io.github.droidkaigi.confsched.dao.SessionDao.update(SourceFile:161)
                         E      at io.github.droidkaigi.confsched.dao.SessionDao.updateAllSync(SourceFile:128)
                         E      at io.github.droidkaigi.confsched.dao.SessionDao$2.execute(SourceFile:138)
                         E      at com.github.gfx.android.orma.OrmaConnection.transactionSync(SourceFile:260)
                         E      ... 4 more
```

## Environment
Nexus 7 (2013)
Android 6.0.1

## Steps to Reproduce
1. Install ver 1.0.1 of the app
2. Go to [DeployGate site](https://deploygate.com/distributions/901884d8a27b8bd9c368109b0cc5c941a6821076#install) and install the app
3 During the installation, a dialog asks the app is not under manged by DeployGate and do you want to manage it with DeployGate? Answer yes to the question
4. After the installation ends, a dialog asks whether opening the app and answer "Open" to the question
5. Launch the app

## Result
At step 5, the app crashes

## Expected result
At step 5, the app does not crash

**Comment by hkurokawa** [comment]
Maybe this bug is specific to DeployGate as I cannot reproduce it with the local builds.

**Comment by hkurokawa** [comment]
Thanks to @gfx, it was turned out that it was as expected. Orma decides whether it should migrate the DB based on the VERSION_CODE of the app when it is a release build. As VERSION_CODE is not changed between the build, it does not do migration.

According to @gfx, he has a plan to improve that behaviour.

Anyway, it should not occur on the builds on Google Play (as we have to increment VERSION_CODE anyway), I am closing the issue.
