### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Failure saving state: active SupportMapFragment{31730d3b} has cleared index: -1

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#246]
It might be already fixed.

```java
Fatal Exception: java.lang.IllegalStateException: Failure saving state: active SupportMapFragment{31730d3b} has cleared index: -1
       at android.support.v4.app.FragmentManagerImpl.saveAllState(SourceFile:1824)
       at android.support.v4.app.Fragment.performSaveInstanceState(SourceFile:2111)
       at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(SourceFile:1767)
       at android.support.v4.app.FragmentManagerImpl.saveAllState(SourceFile:1835)
       at android.support.v4.app.FragmentController.saveAllState(SourceFile:125)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(SourceFile:523)
       at io.github.droidkaigi.confsched.activity.MainActivity.onSaveInstanceState(SourceFile:89)
       at android.app.Activity.performSaveInstanceState(Activity.java:1383)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1286)
       at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4473)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3845)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3908)
       at android.app.ActivityThread.access$1200(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by futabooo** [comment]
Same error occurred...
commit hash is 07889da5fbaedf11658a17a6936ed277bf473b35

## Steps to reproduce
1. Clean install the app. (developDebug)
2. Launch the app
3. Open the map screen
4. Open the another screen on MainActivity.(ex. All sessions)
5. Transition to other Activities.(ex. SessionDetail)

## Result
At step 5, this error occurred

```
java.lang.IllegalStateException: Failure saving state: active SupportMapFragment{3df21b8} has cleared index: -1
at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1824
at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2111)
at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1767)
at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1835)
at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:125)
at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:523)
at io.github.droidkaigi.confsched.activity.MainActivity.onSaveInstanceState(MainActivity.java:90)
at android.app.Activity.performSaveInstanceState(Activity.java:1320)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1293)
at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4064)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3475)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3531)
at android.app.ActivityThread.access$1100(ActivityThread.java:156)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5373)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by Jitendran** [comment]
You are removing wrong Fragment(Map Fragment), You have to remove your java class Fragment.

**Comment by konifar** [comment]
:eyes:

**Comment by hkurokawa** [comment]
I believe it's already fixed with https://github.com/konifar/droidkaigi2016/pull/263

**Comment by konifar** [comment]
@Jitendran Thanks for the comment!
As @hkurokawa said, I thought it had been fixed https://github.com/konifar/droidkaigi2016/pull/263
If you still got the same error, can you tell me the detail? 🙇

**Comment by Jitendran** [comment]
Thanks Yusuke,

The probles have resoled....
