### ISSUE TITLE
Crash in Orma

### ISSUE THREAD

**Issue by gfx** [konifar/droidkaigi2016#318]
Will fix this issue :sob: 

```
E/AndroidRuntime( 6563): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 6563): Process: io.github.droidkaigi.confsched, PID: 6563
E/AndroidRuntime( 6563): android.database.sqlite.SQLiteException: near "OFF": syntax error (code 1): , while compiling: PRAGMA foreign_keys OFF
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:895)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:506)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
E/AndroidRuntime( 6563): 	at com.github.gfx.android.orma.migration.AbstractMigrationEngine.transaction(SourceFile:88)
E/AndroidRuntime( 6563): 	at com.github.gfx.android.orma.migration.SchemaDiffMigration.executeStatements(SourceFile:335)
E/AndroidRuntime( 6563): 	at com.github.gfx.android.orma.migration.SchemaDiffMigration.start(SourceFile:107)
E/AndroidRuntime( 6563): 	at com.github.gfx.android.orma.OrmaConnection.onOpen(SourceFile:363)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266)
E/AndroidRuntime( 6563): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
E/AndroidRuntime( 6563): 	at com.github.gfx.android.orma.OrmaConnection.getWritableDatabase(SourceFile:115)
E/AndroidRuntime( 6563): 	at com.github.gfx.android.orma.OrmaConnection.transactionSync(SourceFile:243)
E/AndroidRuntime( 6563): 	at com.github.gfx.android.orma.OrmaConnection$2.run(SourceFile:262)
E/AndroidRuntime( 6563): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 6563): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 6563): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by konifar** [comment]
:sob:

**Comment by konifar** [comment]
Awesome...! What a quick fix.
