### ISSUE TITLE
Azure integration

### ISSUE THREAD

**Issue by volkanduru** [konifar/droidkaigi2016#401]
I am trying add project Azure SDK, but project not running. I guess, this problem a conflicts other library (like DI).. I don't understand what is wrong. I only add gradle, dependencies Azure Android SDK below; 

compile 'com.microsoft.azure:azure-mobile-android:3.1.0'

I get this error; 
```
08-26 11:52:05.035 25689-25689/io.github.droidkaigi.confsched.develop.debug E/dalvikvm: Could not find class 'io.github.droidkaigi.confsched.di.DaggerAppComponent$ActivityComponentImpl', referenced from method io.github.droidkaigi.confsched.di.DaggerAppComponent.plus
08-26 11:52:05.045 25689-25689/io.github.droidkaigi.confsched.develop.debug E/dalvikvm: Could not find class 'okhttp3.Cache', referenced from method io.github.droidkaigi.confsched.di.AppModule.provideHttpClient
08-26 11:52:05.045 25689-25689/io.github.droidkaigi.confsched.develop.debug E/dalvikvm: Could not find class 'io.github.droidkaigi.confsched.di.AppModule$1', referenced from method io.github.droidkaigi.confsched.di.AppModule.provideOrmaDatabase
08-26 11:52:05.045 25689-25689/io.github.droidkaigi.confsched.develop.debug E/dalvikvm: Could not find class 'io.github.droidkaigi.confsched.api.RequestInterceptor', referenced from method io.github.droidkaigi.confsched.di.AppModule.provideRequestInterceptor
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime: FATAL EXCEPTION: main
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime: java.lang.NoClassDefFoundError: io.github.droidkaigi.confsched.di.AppModule_ProvideContextFactory
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at io.github.droidkaigi.confsched.di.DaggerAppComponent.initialize(DaggerAppComponent.java:101)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at io.github.droidkaigi.confsched.di.DaggerAppComponent.<init>(DaggerAppComponent.java:91)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at io.github.droidkaigi.confsched.di.DaggerAppComponent.<init>(DaggerAppComponent.java:60)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at io.github.droidkaigi.confsched.di.DaggerAppComponent$Builder.build(DaggerAppComponent.java:169)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at io.github.droidkaigi.confsched.MainApplication.onCreate(MainApplication.java:31)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4684)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at android.app.ActivityThread.access$1400(ActivityThread.java:159)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5419)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
08-26 11:52:05.050 25689-25689/io.github.droidkaigi.confsched.develop.debug E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

Thank you for your help..

**Comment by hotchemi** [comment]
@volkanduru Please invalid cache and restart android studio.
And we don't have any plan to add azure-mobile-android, so let me close this issue.
